baseURL: https://vonhartz.info
languageCode: en-us
title: Jan Ole von Hartz
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Hello World 
        Content: I am a PhD student in neurorobotics and robot learning at the University of Freiburg.

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/vonHartz"
        - name: "rss"
          url: "https://vonhartz.info/index.xml"
    ShowReadingTime: true
    author: "Jan Ole von Hartz"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: cv
          name: CV
          url: /pages/cv/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 30
